# -*- coding: utf-8 -*-
"""bazybazy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7Ie867oNNIlI59lRVRtva5NokFueoQ9
"""

import streamlit as st
from supabase import create_client, Client

# Konfiguracja połączenia z Supabase
# Dane zostaną pobrane z Streamlit Secrets dla bezpieczeństwa
url: str = st.secrets["SUPABASE_URL"]
key: str = st.secrets["SUPABASE_KEY"]
supabase: Client = create_client(url, key)

st.title("📦 System Zarządzania Produktami")

tab1, tab2, tab3 = st.tabs(["Dodaj Kategorię", "Dodaj Produkt", "Podgląd Bazy"])

# --- TAB 1: DODAWANIE KATEGORII ---
with tab1:
    st.header("Dodaj nową kategorię")
    with st.form("category_form"):
        kat_nazwa = st.text_input("Nazwa kategorii")
        kat_opis = st.text_area("Opis kategorii")
        submit_kat = st.form_submit_button("Zapisz kategorię")

        if submit_kat:
            if kat_nazwa:
                data = {"nazwa": kat_nazwa, "opis": kat_opis}
                try:
                    supabase.table("kategoria").insert(data).execute()
                    st.success(f"Kategoria '{kat_nazwa}' została dodana!")
                except Exception as e:
                    st.error(f"Błąd: {e}")
            else:
                st.warning("Nazwa kategorii jest wymagana.")

# --- TAB 2: DODAWANIE PRODUKTU ---
with tab2:
    st.header("Dodaj nowy produkt")

    # Pobieramy aktualne kategorie do rozwijanej listy
    try:
        kategorie_res = supabase.table("kategoria").select("id, nazwa").execute()
        kategorie_dict = {item['nazwa']: item['id'] for item in kategorie_res.data}
        lista_nazw_kat = list(kategorie_dict.keys())
    except Exception as e:
        st.error("Nie udało się pobrać kategorii.")
        lista_nazw_kat = []

    with st.form("product_form"):
        prod_nazwa = st.text_input("Nazwa produktu")
        prod_liczba = st.number_input("Liczba (szt.)", min_value=0, step=1)
        prod_cena = st.number_input("Cena", min_value=0.0, format="%.2f")
        wybrana_kat = st.selectbox("Wybierz kategorię", options=lista_nazw_kat)

        submit_prod = st.form_submit_button("Zapisz produkt")

        if submit_prod:
            if prod_nazwa and wybrana_kat:
                product_data = {
                    "nazwa": prod_nazwa,
                    "liczba": prod_liczba,
                    "cena": prod_cena,
                    "kategoria_id": kategorie_dict[wybrana_kat]
                }
                try:
                    supabase.table("produkty").insert(product_data).execute()
                    st.success(f"Produkt '{prod_nazwa}' został dodany!")
                except Exception as e:
                    st.error(f"Błąd: {e}")
            else:
                st.warning("Wypełnij nazwę produktu i wybierz kategorię.")

# --- TAB 3: PODGLĄD DANYCH ---
with tab3:
    st.header("Aktualny stan magazynowy")
    if st.button("Odśwież dane"):
        # Pobieranie produktów wraz z nazwami kategorii (Join)
        res = supabase.table("produkty").select("nazwa, liczba, cena, kategoria(nazwa)").execute()
        if res.data:
            st.table(res.data)
        else:
            st.info("Baza jest pusta.")